// Generated by CoffeeScript 1.10.0
describe("PrimesView", function() {
  var view;
  view = new PrimesView;
  beforeEach(function() {
    return view = new PrimesView;
  });
  it("can get a text input box", function() {
    expect(view.getTextInput()).toContain('input type="text"');
    return expect(view.getTextInput()).toHaveClass('numInput');
  });
  it("can get an output label", function() {
    return expect(view.getOutputLabel()).toHaveClass('primesList');
  });
  return it("can get the html with the input and label", function() {
    expect(view.render().$el.html()).toContain('numInput');
    return expect(view.render().$el.html()).toContain('primesList');
  });
});
