// Generated by CoffeeScript 1.10.0
var PrimesView,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

PrimesView = (function(superClass) {
  extend(PrimesView, superClass);

  function PrimesView() {
    return PrimesView.__super__.constructor.apply(this, arguments);
  }

  PrimesView.prototype.initialize = function() {};

  PrimesView.prototype.getTextInput = function() {
    return '<h6>Enter a Number:</h6><input type="text" name="numInput" class="numInput">';
  };

  PrimesView.prototype.getOutputLabel = function() {
    return '<h6> Primes: <h6 class="primesList"> </h6> </h6>';
  };

  PrimesView.prototype.render = function() {
    this.$el.html(this.getTextInput() + this.getOutputLabel());
    return this;
  };

  return PrimesView;

})(Backbone.View);
