// Generated by CoffeeScript 1.10.0
var PrimesGenerator;

PrimesGenerator = (function() {
  function PrimesGenerator() {}

  PrimesGenerator.prototype.generatePrimes = function(number) {
    var num, primesList;
    primesList = [];
    num = 2;
    while (number > 1) {
      if (number % num === 0) {
        number = number / num;
        primesList.push(num);
      } else {
        num = num + 1;
      }
    }
    return primesList;
  };

  return PrimesGenerator;

})();
