// Generated by CoffeeScript 1.10.0
var PrimesGenerator;

PrimesGenerator = (function() {
  function PrimesGenerator() {}

  PrimesGenerator.prototype.generatePrimes = function(number) {
    return number;
  };

  return PrimesGenerator;

})();
